name: prueba CI/CD

on:
  push:
    branches:
      - main

jobs:
  prueba_1:
    runs-on: ubuntu-18.04
    steps:
      - name: echo the message
        run: |
          echo 'hola esto es una prueba d eun workflow'
